version: "3.9"
services:
  samba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      # Use a high port to avoid conflicts with a locally running SMB server
      - "1445:445"
    volumes:
      - ./example:/var/sambashare:rw
    environment:
      SMB_USER: testuser
      SMB_PASS: testpass
      # Optional: 
      # SMB_LOGLEVEL: 1
