version: "3.9"
services:
  samba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "445:445"
    environment:
      SMB_USER: testuser
      SMB_PASS: testpass
    volumes:
      - ./example:/var/sambashare:rw
