version: "3.9"
services:
  samba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:445:445
    volumes:
      # Overlay-mount the password files
      - ./example/passwd:/etc/passwd:rw
      - ./example/shadow:/etc/shadow:rw
      - ./example/smbpasswd:/var/lib/samba/private/smbpasswd:rw
      
      # Overlay-mount the config and share files
      - ./example/smb.conf:/etc/samba/smb.conf:ro
      - ./example/sambashare:/var/sambashare:rw
