version: "3.9"
services:
  samba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "1445:445"
    volumes:
      - ./example:/var/sambashare:rw
    environment:
      SMB_USER: testuser
      SMB_PASS: testpass
      # Optional: 
      SMB_LOGLEVEL: 1 passdb:5 auth:5
